"use client";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
type Creator = { creatorId: string; username: string; daysSinceJoining: number };
type Progress = { welcomeDate?: string; training1Date?: string; training2Date?: string; training3Date?: string; training4Date?: string; feedbackWeek1?: boolean; feedbackWeek2?: boolean; feedbackWeek1Url?: string; feedbackWeek2Url?: string; appLinkSent?: boolean; pfpChanged?: boolean; submitted?: boolean; confirmed?: boolean };
const accents: Record<string, string> = { paradise: "#d6a65e", respawn: "#28d7c3", horizon: "#f97316", trident: "#38bdf8" };
const trainingFields = ["training1Date", "training2Date", "training3Date", "training4Date"] as const;
export default function OnboardingPage() {
  const { agency, manager } = useParams<{ agency: string; manager: string }>(); const searchParams = useSearchParams(); const managerLabel = searchParams.get("label"); const [creators, setCreators] = useState<Creator[]>([]); const [progress, setProgress] = useState<Record<string, Progress>>({}); const [uploading, setUploading] = useState(""); const fileInputs = useRef<Record<string, HTMLInputElement | null>>({}); const id = (username: string) => `${agency}:${manager}:${creators.find((creator) => creator.username === username)?.creatorId || username}`;
  useEffect(() => { Promise.all([fetch(`/api/onboarding?manager=${encodeURIComponent(manager)}&agency=${agency}`).then((r) => r.json()), fetch("/api/onboarding-progress").then((r) => r.json())]).then(([onboarding, saved]) => { setProgress(saved.entries || {}); setCreators((onboarding.creators || []).filter((creator: Creator) => !saved.entries?.[`${agency}:${manager}:${creator.creatorId}`]?.confirmed)); }); }, [agency, manager]);
  async function save(username: string, update: Progress) { const entry = { agency, manager, username, ...(progress[id(username)] || {}), ...update }; setProgress((current) => ({ ...current, [id(username)]: entry })); await fetch("/api/onboarding-progress", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "update", id: id(username), entry }) }); }
  async function upload(username: string, week: 1 | 2, file: File) { const key = `${username}-${week}`; setUploading(key); try { const form = new FormData(); form.set("file", file); form.set("agency", agency); form.set("manager", manager); form.set("username", username); form.set("week", String(week)); const response = await fetch("/api/onboarding-upload", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Upload failed."); await save(username, week === 1 ? { feedbackWeek1: true, feedbackWeek1Url: data.url } : { feedbackWeek2: true, feedbackWeek2Url: data.url }); } catch (error) { window.alert(error instanceof Error ? error.message : "Could not upload screenshot."); } finally { setUploading(""); } }
  return <main className="onboarding-page" style={{ "--onboarding-accent": accents[agency] } as React.CSSProperties}><Link href={`/agency/${agency}/managers/${manager}${managerLabel ? `?label=${encodeURIComponent(managerLabel)}` : ""}`}>BACK TO MANAGER PORTAL</Link><div className="onboarding-title"><p>MANAGER WORKSPACE</p><h1>ONBOARDING</h1><span>NEW CREATORS FROM THE LAST 14 DAYS</span></div><section className="onboarding-cards">{creators.map((creator) => { const item = progress[id(creator.username)] || {}; return <article key={creator.username} className="onboarding-card"><header><strong>@{creator.username}</strong><span>DAY {creator.daysSinceJoining}</span></header><div className="onboarding-tasks onboarding-tasks-expanded"><label><span>WELCOME MESSAGE</span><input type="date" value={item.welcomeDate || ""} onChange={(event) => void save(creator.username, { welcomeDate: event.target.value })}/></label>{trainingFields.map((field, index) => <label key={field}><span>TRAINING CALL {index + 1}</span><input type="date" value={item[field] || ""} onChange={(event) => void save(creator.username, { [field]: event.target.value })}/></label>)}{([1,2] as const).map((week) => { const field = week === 1 ? "feedbackWeek1" : "feedbackWeek2"; const url = week === 1 ? item.feedbackWeek1Url : item.feedbackWeek2Url; const key = `${creator.username}-${week}`; return <label key={week}><span>FEEDBACK · WEEK {week}</span><div><input type="checkbox" checked={!!item[field]} onChange={(event) => void save(creator.username, { [field]: event.target.checked })}/><input ref={(node) => { fileInputs.current[key] = node; }} className="onboarding-file-input" type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(creator.username, week, file); }}/><button type="button" onClick={() => fileInputs.current[key]?.click()}>{uploading === key ? "UPLOADING..." : url ? "REPLACE SCREENSHOT" : "UPLOAD SCREENSHOT"}</button></div></label>; })}<label><span>FIRST CLASS APP LINK SENT</span><input type="checkbox" checked={!!item.appLinkSent} onChange={(event) => void save(creator.username, { appLinkSent: event.target.checked })}/></label><label><span>1-1 PROFILE PHOTO UPDATE</span><input type="checkbox" checked={!!item.pfpChanged} onChange={(event) => void save(creator.username, { pfpChanged: event.target.checked })}/></label></div><button type="button" className="complete-onboarding" onClick={() => void save(creator.username, { submitted: true })}>{item.submitted ? "ONBOARDING SENT FOR CONFIRMATION" : "COMPLETE ONBOARDING"}</button></article>; })}{!creators.length && <p className="onboarding-empty">NO NEW CREATORS IN THE LAST 14 DAYS.</p>}</section></main>;
}
