import { NextResponse } from "next/server";
import { submissionsSupabase } from "@/lib/submissions-supabase";

type Task = { id: string; description: string; assignee: "OWN TASK" | "OWNER"; dueDate: string; dueTime: string; highPriority: boolean; createdAt: string; forwardedToOwner?: boolean };
const managerKey = (value: unknown) => String(value || "").toLowerCase().replace(/[^a-z0-9]/g, "");
const storageKey = (manager: string) => `first-class-manager-tasks-${managerKey(manager)}`;
function normalize(input: unknown): Task[] { return (Array.isArray(input) ? input : []).flatMap((item) => { const row = item as Record<string, unknown>; const description = String(row.description || "").trim(); return description ? [{ id: String(row.id || crypto.randomUUID()), description, assignee: String(row.assignee) === "OWNER" ? "OWNER" : "OWN TASK", dueDate: String(row.dueDate || ""), dueTime: String(row.dueTime || ""), highPriority: Boolean(row.highPriority), createdAt: String(row.createdAt || new Date().toISOString()), forwardedToOwner: Boolean(row.forwardedToOwner) }] : []; }); }
async function read(name: string) { const { data, error } = await submissionsSupabase.from("poster_templates").select("template_json").eq("name", name).maybeSingle(); if (error) throw new Error(error.message); return normalize((data?.template_json as { tasks?: unknown } | null)?.tasks); }
export async function GET(request: Request) { try { const manager = new URL(request.url).searchParams.get("manager") || ""; return NextResponse.json({ tasks: await read(storageKey(manager)) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not load tasks." }, { status: 500 }); } }
export async function PUT(request: Request) { try { const body = await request.json(); const manager = String(body.manager || ""); let tasks = normalize(body.tasks); const outgoing = tasks.filter((task) => task.assignee === "OWNER" && !task.forwardedToOwner); if (outgoing.length) { const { data } = await submissionsSupabase.from("poster_templates").select("template_json").eq("name", "agency-task-space").maybeSingle(); const main = ((data?.template_json as { tasks?: unknown } | null)?.tasks as Record<string, unknown>[] || []); const ids = new Set(main.map((task) => String(task.id))); for (const task of outgoing) if (!ids.has(task.id)) main.unshift({ ...task, assignee: "JD / DF", creator: "", complete: false, sourceManager: manager, sourceManagerLabel: String(body.managerLabel || manager) }); tasks = tasks.map((task) => task.assignee === "OWNER" ? { ...task, forwardedToOwner: true } : task); const { error } = await submissionsSupabase.from("poster_templates").upsert({ name: "agency-task-space", template_json: { tasks: main }, background_url: null, updated_at: new Date().toISOString() }, { onConflict: "name" }); if (error) throw new Error(error.message); } const { error } = await submissionsSupabase.from("poster_templates").upsert({ name: storageKey(manager), template_json: { tasks }, background_url: null, updated_at: new Date().toISOString() }, { onConflict: "name" }); if (error) throw new Error(error.message); return NextResponse.json({ tasks }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not save tasks." }, { status: 500 }); } }
