// @ts-nocheck
import { NextResponse } from "next/server";
import { submissionsSupabase } from "@/lib/submissions-supabase";
export const dynamic = "force-dynamic";
const SETTINGS = "quitting-records"; const text = (v: unknown) => String(v || "").trim(); const key = (v: unknown) => text(v).toLowerCase(); const number = (v: unknown) => Number(text(v).replace(/[^\d.-]/g, "")) || 0; const username = (r: Record<string, unknown>) => text(r.creator_username || r["Creator's username"]).replace(/^@/, ""); const manager = (r: Record<string, unknown>) => text(r.manager_email || r.creator_network_manager || r["Creator Network manager"] || r.email) || (/unassigned first class/i.test(text(r.team)) ? "mikehalesjb@gmail.com" : "");
function cleanRecord(value: unknown) { const r = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { username: key(r.username).replace(/^@/, ""), creatorId: text(r.creatorId), managers: Array.isArray(r.managers) ? r.managers.map(text).filter(Boolean) : [], groups: Array.isArray(r.groups) ? r.groups.map(text).filter(Boolean) : [], diamonds: number(r.diamonds), reason: text(r.reason), createdAt: text(r.createdAt) || new Date().toISOString() }; }
async function saved() { const { data, error } = await submissionsSupabase.from("poster_templates").select("template_json").eq("name", SETTINGS).maybeSingle(); if (error) throw new Error(error.message); const entries = Array.isArray((data?.template_json as { records?: unknown[] } | null)?.records) ? (data?.template_json as { records: unknown[] }).records.map(cleanRecord).filter(r => r.username) : []; return entries; }
async function saveRecords(records: ReturnType<typeof cleanRecord>[]) { const { error } = await submissionsSupabase.from("poster_templates").upsert({ name: SETTINGS, template_json: { records }, background_url: null, updated_at: new Date().toISOString() }, { onConflict: "name" }); if (error) throw new Error(error.message); return records; }
export async function GET() { try { return NextResponse.json({ records: await saved() }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not load quitting records." }, { status: 500 }); } }
export async function POST(request: Request) { try { const input = await request.json(); const current = await saved();
  if (input.action === "save") { const updates = (Array.isArray(input.records) ? input.records : []).map(cleanRecord).filter(r => r.username); const byUsername = new Map(current.map(r => [r.username, r])); updates.forEach(r => byUsername.set(r.username, { ...byUsername.get(r.username), ...r, createdAt: byUsername.get(r.username)?.createdAt || r.createdAt })); const records = [...byUsername.values()].sort((a,b) => b.createdAt.localeCompare(a.createdAt)); return NextResponse.json({ records: await saveRecords(records) }); }
  if (input.action === "update-reason") { const name = key(input.username).replace(/^@/, ""); const records = current.map(r => r.username === name ? { ...r, reason: text(input.reason) } : r); if (!current.some(r => r.username === name)) return NextResponse.json({ error: "Quitting record not found." }, { status: 404 }); return NextResponse.json({ records: await saveRecords(records) }); }
  if (input.action === "delete-record") { const name = key(input.username).replace(/^@/, ""); const records = current.filter(r => r.username !== name); if (records.length === current.length) return NextResponse.json({ error: "Quitting record not found." }, { status: 404 }); return NextResponse.json({ records: await saveRecords(records) }); }
  const raw: unknown[] = Array.isArray(input.usernames) ? input.usernames : []; const names = [...new Set(raw.map(v => key(v).replace(/^@/, "")).filter(v => /^[a-z0-9._-]+$/.test(v)))].slice(0,30); if (!names.length) return NextResponse.json({ error: "Paste at least one valid username." }, { status: 400 }); const { data, error } = await submissionsSupabase.from("creator_daily_stats").select("*").in("creator_username", names).or("data_period.is.null,data_period.neq.mature_month_total").order("stat_date", { ascending: true }); if (error) throw new Error(error.message); const rows = (data || []) as Record<string, unknown>[]; return NextResponse.json({ records: names.map(name => { const history = rows.filter(r => key(username(r)) === name); return { username: history[0] ? username(history[0]) : name, creatorId: history.map(r => text(r.creator_id)).find(id => /^\d{10,}$/.test(id)) || "", managers: [...new Set(history.map(manager).filter(Boolean))], groups: [...new Set(history.map(r => text(r.group_name || r.team)).filter(g => g && !/not in a group/i.test(g)))], diamonds: history.reduce((sum,r) => sum + number(r.diamonds),0), reason: "", createdAt: new Date().toISOString() }; }) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not build quitting records." }, { status: 500 }); } }
