import { NextResponse } from "next/server";
import { submissionsSupabase } from "@/lib/submissions-supabase";

export const dynamic = "force-dynamic";
const text = (value: unknown) => String(value || "").trim();
const key = (value: unknown) => text(value).toLowerCase();
const number = (value: unknown) => Number(text(value).replace(/[^\d.-]/g, "")) || 0;
const username = (row: Record<string, unknown>) => text(row.creator_username || row["Creator's username"]).replace(/^@/, "");
const manager = (row: Record<string, unknown>) => text(row.manager_email || row.creator_network_manager || row["Creator Network manager"] || row.email);
export async function POST(request: Request) { try { const input = await request.json(); const rawUsernames: unknown[] = Array.isArray(input.usernames) ? input.usernames : []; const usernames = [...new Set(rawUsernames.map((name: unknown) => key(name).replace(/^@/, "")).filter((name) => /^[a-z0-9._-]+$/.test(name)))].slice(0, 30); if (!usernames.length) return NextResponse.json({ error: "Paste at least one valid username." }, { status: 400 }); const rows: Record<string, unknown>[] = []; for (let from = 0, more = true; more; from += 1000) { const { data, error } = await submissionsSupabase.from("creator_daily_stats").select("*").in("creator_username", usernames).or("data_period.is.null,data_period.neq.mature_month_total").order("stat_date", { ascending: true }).range(from, from + 999); if (error) throw new Error(error.message); const batch = (data || []) as Record<string, unknown>[]; rows.push(...batch); more = batch.length === 1000; } const records = usernames.map((name) => { const history = rows.filter((row) => key(username(row)) === name).sort((a, b) => text(a.stat_date).localeCompare(text(b.stat_date))); const managers = [...new Set(history.map(manager).filter(Boolean))]; const groups = [...new Set(history.map((row) => text(row.group_name || row.team)).filter(Boolean).filter((group) => !/not in a group/i.test(group)))]; const creatorId = history.map((row) => text(row.creator_id)).find((id) => /^\d{10,}$/.test(id)) || ""; return { username: history[0] ? username(history[0]) : name, creatorId, managers, groups, diamonds: history.reduce((sum, row) => sum + number(row.diamonds), 0), records: history.length }; }); return NextResponse.json({ records }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not build quitting records." }, { status: 500 }); } }
