export const FIRST_CLASS_EVENT = {
  name: "First Class: Ascend",
  creatorLink: "/live/7xq9v2-first-class",
  teamCount: 20,
  creatorsPerTeam: 36,
};

export type TournamentCreator = {
  username: string;
  teamNumber: number;
  slot: number;
};

// Replace these placeholders with real TikTok usernames when the draw is final.
// The live leaderboard, totals, and profile-photo lookup start working automatically.
const TEAM_USERNAMES = [
  "jdmpixxie adam_gym234 ghostboy2034 aycee_24s ashtonpye crazygallie999 alfie.434 lilmissmaudi5 lorna_fletcher_97 stockportgamer 1freyawinter kaizer9025 scarx428 h0llsxoo7 rachyandburp astryxplays soulbeliever5 xlucy.rxbertson jeffreythechef cleo.toll19 dev1lsdaughter mumma_2_angels courtneyw_25 resili3n_t your.mush.aj xo.chloe.7x unisonraid9 miss1of1xx jay_lufc93 joshtuff2 cuzzplays8 blondieee07 tuttifruityy92 queen.ginger42 eviekerr14 dragonboy3332",
  "arrcch libs.xo16 dylan221250 cieran01 leahkircali717 jackbg_offical privv.amanda123 xchloe_kirby.x amy.x2006 noah.j53bu amymt25 kieransmithmilner kaiden.armstrong07 scottjherd coran.purser inkedqueengaming kickstarts_x shys.secretxo xmiasmithx1 ih8cheese2 jay_rich.xox01x pidgeknight kayleighlou1104 urbunsxoxo daniclark.01 theblueprint_gamers lizzie96.x nauzia theencouragingmartin tanyajcox14 kiekiedoesit carelessclothing222 wdbc_irish_rebel itzz_xnyxx joe.games000 phil7645",
  "mrsmrsmcdermott1 gemmaabyrne flexzontik justgooodcontent kayleestewarttx its..mee...laura steven.m46 balmyhercules94 liamj99_ quotes4u_first_class jake_pearson_1 ogisgaming1 ashsaxon stuartjarv thejess.szulc_diary pollyfirstclass bellescupids sonofanarchygaming0 sodi_rl cordeliachatfield vibes010998 libx23 katelyn_dono4 _alchemizedmusic_ rich35ukuk 39 wolfmangaming voidbunnyx _prettyforlife_ itslcbreezyofficial 39 lee394152 tamika_heath23 f14ndr kpactivebushy chocolatecookie200",
  "dylanjinks lukealbert4 kayleigh.jade6 louuuuu97 shell5707 demilea_05 loudengaming ronniefieldd onlyteeteee princesskerrie1 kirstys_00 luca..ii3 officialmtfcbailey07 georgialillyyy midnighthuntrx scaryterrylive07 _its_5pm_somewhere_ lindzzdelaney n0isy_blake itzyaboyjaxon shelby.blackmore sam.bpl06 kaciegresswell0 xspiritedhaku ch10eanne brooke.mayhew xxjodie.footexx tinkybellgaming909 angelmama_dana valentina.bergonzixx doughnut1402 kelseyc_ shi_ward25 themooseuk meekasprivx",
  "marisaxoxo13 maddiedobson._ dens2511 emily17mc maxbutler.4 georgiabrookss20 jamie_lee1997 ibzz007 kirsty.wells5 melaniemcallister3 meganxrowe livs_privxx5 boxer198818 itzzzrob3 laceyjxx07 welshsniperuk ccourt_2021 womanlikedanii gaming.on.me.tod brendonr456 sophiescosygames kilbridex liv_lillico5678 duckie_of_darkness x.becky.dixon.x brandon_the_cheese samanthajane1992 tarajane1524 datkid.lzz thelastwallpainter nateorplate 9doesgym billackleton2026 louisaroe83 ttv.bxnoj",
  "kayjb_3 soph.x19x al1ceroseb ellabyrne1904 tommyj927 zaliheyoncuofficial itslulu225 jaime.jx emilyoverton865 garciathepolarbear xx.skye.08 liamftnw untickytockytash benkanan bradleyjeavongoldensnitc louiseobrien920 amyleigh207 therealdillshady unknxwn011314 olliblakeleymusic christina_eva.xo ls00901 x.psychobitchh.xo adaminnes5 kaylaaax0 amyloxley lucifersdollyxo cathtiktok06 rooroo2166 danonwrestling pissedasusual flipbookgaming lgwstreams1 kamilabielicka official.amzzz",
  "s.isbackbaby69 vardoxen stephen14444 elliex035 cerilaw83 owen28990 mj.bx07 mavismim abbiesworld0605 sasha.aqua.agency jayjayezt1 di.mw1804 laurencarter73 cerysnield anonymouschild78 essexdollabi paigeleigh788 zoedangerjade benfurlong470 madz.2600 brandon.marshall29 bruzy19 maiawilliams_ pocket_rocket900 mrelite_respawan_teamfox shaysullivan316 andypagey sweetbutpsycho1997 skystockton21 sarahbp89 oldcouchgamer kerrig03 channyxxxxx deadlywar03 shadowhexjxmes1",
  "failuretothrive2008 libbyamberxoxo lissy.grwm0 taylorcarter87 courtsxox33 xyabear22 jay.webbxx sebachu999 demi_backup33 shan.non20256 matthew.steel6 ella_quinnxx louxx88 corie.watkins purpledrilly jodie.harvey dollycollins1x dillon.davis5 miyarose178 mo.ali3614 xsmxrxx xhollscourtsx chaptersofchaos666 couchpotatoash kayla_northeast honeybeee622 ali6969xoxo tdocherty0 itsmisslinaa quaylian cynocles em1lygwen cerys_williamz hannahxjoby xxchanchanxx04",
  "turbotagz charlieavamaai16 mrssparky0 browning_2004 kashfromda9official leahcooper203 rubylou050 rustytrigger_1 lily.wills25 powderedandproblematic leahlaunders20 charlotte_mcainey_12 suey9219 xislax2 lisar_on_jaro xemz_5x ells.xcc1 milliejade004 dannielleibbotson summer_taylor7 nelly.parsnipsx40 sophie.x_21 bondedfx rob.hunter87 itsnerdyyc ghostface_gaming james.pike.aka.pi nick.sandy7 homergaming1ttv selfgrowthwithtraceyj lilyb_x_ raven_bloodrose_bam shivsbackup alfieglxdwin dragongirl362",
  "dam_it_chan sgtgramps jacobr015 z.diness goldengun_2 legallymixed maikatemc titch_5 leanneonlife shannonloganxox tina_be00 6quack7 mads.mcleod16 rileyup06 mace6760 waifbaes xo_faye_xo18 holzystreams angel_93_14 theruleofghoul no1fitzy aviationsoph2006 jadesmith0250 hollymay_2007 bradddzsj karolina.l06 mads.ell22 chelsea.ward80 shannonmx2 beth_rowlands21 hazstacksgwop1 angelinaroyle17 aims.ad77 matt_gaming80 bastreams01",
  "2026_phyco leeimahn96 j.wliveacc charlievenables2 bexaroonie its_watsonspamm tezz1994 abbiegrant26 kets540 smokeandstilettos emma_2025xx willjohno97 _lucy_no1 piercdntattdd sdplays94 y0ur_l0cal_j nutty_nat17 sarafraser82 shelbywigfield 4rr0n_b graveyardlace hannahbrissenden12 jordan.sears_ callsignviper20 gamingwithcookiz shareenafenwick scottishcammy xaraoneill aronmirmusic lilo_foreverx slappyskillzgaming quin_oflynn katie_mellor2001 ukswagashotz patriziatigue3",
  "x_cj_tokens_x kyzwrld1 sam252410 recoverywithlily2.2 elllllsssssss_xo23 white.trxsh101 austeja_123k2004 rhir3a pyroindigame janieb551 queenangeltv teegz9971 nyriqontop _.reyno xx_star_xx30 mollsjadex owen.whittaker0 mrjigglebac xkialouiseee smilie848 izzybusking inactiveuser2999 theofficialwill007 gavzywz nikita123455 mikehalesmma activ3_j7 slamth0t tny.2.0 jcxttt chelsnorton788 morgan_wynn25 astromort .leonajayne rxchierich",
  "robscottw caitlinjervis68 flatline_official kitokovacs raachlouisexxx trevortilcock5 penii1722 starlight00p00 lewisalanhardacre henrymunslow itsriverlea jess_22_c .jackhill3 sophiehaynes37 xephno1 j96x01 megs_lilyxoxo melissaah1997 itsyouboy96 jp_0251 f3arax jodiemccaffrey2 a1.backupp3 x.alice.x04 roootsyy strorny03 elowenmagik dr.donut045 itz._.b00 ..tyler_xanderc urfavv_caz lillimae_20 kyle94678 bonnieclydescooking westhamdan5",
  "laurenleig.h josh4pffitness26 alisha06 thackers123 ateamxo lonnell6 that.mum.over.the freddie.toll1 bailedonbails upliftingjono deannalangham07 veronica_rose22 kitch469 callum.072 carys.windibank codexsystems chloes1252 damo_bafc thee.mr.0 katiemilne05 teresadonovan12 grannybasheraaron69 2_57am tix_privv thepanicbandit keirdaleoakesss q4mzs1 angelinagittoesxmain sharna.xxx itsnotmeitsyoux2 mattyjf_21 mrspopeye26 autistic_streamer bowen_142 andypandy3762",
  "harryjonesey sambaileysingerofficial theoneinthehat wahid.hussain928 stepbystepwithjack addy_w786 queeniesouthxx ashleygardner93 sc95__ gethinmayers usernothere251 qdedbyjiggle 420_unknown.c1 leonathegirl4 chloefredajanetarot jakeandbailey0 jasminaanastasija0 poppytownend iswxz._.20 kaydkamara xtaylameaglen robertparrott4 lyndsey299 kayla_181206 adelleturnerr hexsc lewismurray51 ethan_jones_22 nicolecarrott baby_mama29_ chloe.roberts111 harrisongunn4 mister.robert.house mommabrookes92 jennygump11",
  "arabellama_y paigeoliviaax1 poppy_cooper06 sadeelizabethxx soph06782 lucy_ann1481 cheeky4787 xlaurenjohnson_a0rrnb3ll uknwn06 miss_readxo x_ruby_x3 harleyj23x zcastle1234 chrisinit89 dylan.cryo whossoleice chloechapman2003 leahx.06 bigdadgaming mikeybrenmusic chrisdoestoomuch01 eilismoore2023 lacey.xo.1 amber20269 klslouis shannon.clarke070 misschae.x09 hobbsherbs1 faxthemachine irrelevant.white.dee kraken25000 gamervet9 shazisback shannonlouiseshac kombojones",
  "crystalrose.rx jayyy02413 brandyfalconer theartfulsunshine nalathehuntress meganstone71 leighanne.thomson joshuahurd1 captainbeard22 cameron_daviesmusic nataliejaynexx stacieholton1 eggbertplays dobbie.9718 charliec203 ameliapipes1 itslouisnotlewis joshyouare_holding willowde_vil1 billie.anderson73 clashelniko .jason.07 gtk.ghost.s bpeakyy bethsharples3 britishscottuk tazzzex3 iconicamzyxo xiiifr3sh lianafoster tiarniigeorgette.x kamron621 chuckymufc chefmang01 csphantom2",
  "glenifarr grantsmithgks kleelou_ygam_kiki hannakingwoodward v0x____ fearne.rgx evalilyox primalnxs cutiechaos35 saraaelisabeth kaidensc07 baby_b277 ragequitqueen8 _zeedz steolav connor.mindset evasvirtualdiary seenbutnotheard25 xshay_25x treacts369 jacko.264 k3rr1_006 summerlouisexxxxxxxxxxxx krishodsoll the.pressfactory nekro858 summer_mariex0 webby.editz kiera.182 millie2005.xo d0llf4cej3ss budgie0838 athenahughes0 ayleighframexxxx dylz188",
  "xomarky soph99004 rborowik8 simonelyons0 pappa1901 theaudhdgardener jade.xo21 queendee3232 yo.its.your.mush.aj deaks89 amberjayne885 tashbash21 meg_chris230903 tuthpick_0 my_oldrover jemma.rebecca lauzza_ytlq chloeplummer._ marshalldagless1 alicia.jo180102 madshooterpro xx.bw.xx mollyphillips24 shan.xx45 daktit_04 leanneadams29 benrogers99 hb_.x1 sumz818 unknowgirl00097 abbsxoxo0 georgiaa.dale xegjae csgswizzy aaron_brown27",
  "tkaysx lukebennett170.2 xcarlymx benofwands bam_bam9443 tdawg350 candicel05 milliemay.x07 indymountainstv darknkght92 lulureloaded hollyshepherd7 sadiebaby335 cjames1135 olocke27 gemma.editz itssophiejadex beyondevan 3hearts1journey0 lyss_the_snail alwenmorris65 cjmgaming tvp_trip lissac20 lozza2706 hadleighbeau dee_dog13 savy_xox0 beth.172 robbinshae n4deem75 billy_869_ tia_xxx_xx xxpaigeyloudxx missamberdoo",
];

export const FIRST_CLASS_CREATORS: TournamentCreator[] = TEAM_USERNAMES.flatMap((team, teamIndex) =>
  team.split(" ").map((username, slot) => ({ username, teamNumber: teamIndex + 1, slot: slot + 1 }))
);

export function isPlaceholderCreator(username: string) {
  return /^creator-\d+$/i.test(username);
}
