import { NextResponse } from "next/server";
import { submissionsSupabase } from "@/lib/submissions-supabase";

const SETTINGS_NAME = "battle-network-settings";
const EXTERNAL_AGENCY = { id: "external-agency", name: "EXTERNAL AGENCY", password: "BATTLE", accent: "#94a3b8", logoUrl: "" };
const BUILT_IN_AGENCIES = [
  { id: "paradise", name: "PARADISE", password: "GEE56", accent: "#d6a65e", logoUrl: "/agency-logos/paradise.png" },
  { id: "respawn", name: "RESPAWN", password: "NICK12", accent: "#28d7c3", logoUrl: "/agency-logos/respawn.png" },
  { id: "horizon", name: "HORIZON", password: "DENS34", accent: "#f97316", logoUrl: "/agency-logos/horizon.png" },
  { id: "trident", name: "TRIDENT", password: "MARCY78", accent: "#38bdf8", logoUrl: "/agency-logos/trident.png" },
  { id: "first-class-dan-james", name: "FIRST CLASS DAN / JAMES", password: "DAN44", accent: "#facc15", logoUrl: "/world-cup-2026/agencies/first-class.png" },
  { id: "honey-bloom", name: "HONEY BLOOM", password: "ABY33", accent: "#f5b942", logoUrl: "" },
  EXTERNAL_AGENCY,
];

type Agency = { id: string; name: string; password: string; accent: string; logoUrl?: string; externalOnly?: boolean };
type Battle = { id: string; agencyId: string; weekStart: string; day: string; creatorUsername: string; manager: string; size: string; powerUps: "POWER-UPS ALLOWED" | "NPU"; requestedTime: string; actualTime: string; opponentBattleId?: string; createdAt: string };
type CardLayout = Record<"home" | "time" | "opponent" | "actions", { x: number; y: number }>;
type CardTypography = { username: number; manager: number; heading: number; time: number };
type Store = { agencies?: Agency[]; battles?: Battle[]; cardLayout?: CardLayout; cardTypography?: CardTypography };
type AssignmentSettings = { managerGroups?: Record<string, string>; managerNames?: Record<string, string> };

function key(value: string) { return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function publicAgency(agency: Agency) { const { password: _password, ...publicValue } = agency; return publicValue; }
function normaliseBattle(value: unknown): Battle | null { const row = value as Record<string, unknown>; const creatorUsername = String(row?.creatorUsername || "").trim().replace(/^@/, ""); const agencyId = key(String(row?.agencyId || "")); if (!creatorUsername || !agencyId) return null; return { id: String(row.id || crypto.randomUUID()), agencyId, weekStart: String(row.weekStart || ""), day: String(row.day || "MONDAY"), creatorUsername, manager: String(row.manager || "").trim(), size: String(row.size || "LESS THAN 1K"), powerUps: String(row.powerUps || "").toUpperCase() === "NPU" ? "NPU" : "POWER-UPS ALLOWED", requestedTime: String(row.requestedTime || ""), actualTime: String(row.actualTime || row.requestedTime || ""), opponentBattleId: String(row.opponentBattleId || "") || undefined, createdAt: String(row.createdAt || new Date().toISOString()) }; }
function normaliseStore(value: unknown): Store { const raw = (value || {}) as Store; const custom = Array.isArray(raw.agencies) ? raw.agencies.filter((agency): agency is Agency => !!agency?.id && !!agency?.name && (!!agency?.password || Boolean(agency?.externalOnly))).map((agency) => ({ ...agency, id: key(agency.id), name: agency.name.toUpperCase(), accent: agency.accent || "#94a3b8", password: agency.password || "EXTERNAL" })) : []; const agencies = [...BUILT_IN_AGENCIES, ...custom.filter((agency) => !BUILT_IN_AGENCIES.some((builtIn) => builtIn.id === agency.id))]; const battles = Array.isArray(raw.battles) ? raw.battles.map(normaliseBattle).filter((battle): battle is Battle => !!battle) : []; return { agencies, battles }; }
async function readStore() { const { data, error } = await submissionsSupabase.from("poster_templates").select("template_json").eq("name", SETTINGS_NAME).maybeSingle(); if (error) throw new Error(error.message); return normaliseStore((data?.template_json as Store | null) || {}); }
async function writeStore(store: Store) { const current = await readStore(); const next: Store = { ...store, cardLayout: store.cardLayout || current.cardLayout, cardTypography: store.cardTypography || current.cardTypography }; const { error } = await submissionsSupabase.from("poster_templates").upsert({ name: SETTINGS_NAME, template_json: next, background_url: null, updated_at: new Date().toISOString() }, { onConflict: "name" }); if (error) throw new Error(error.message); }

async function managerOptions() {
  const { data } = await submissionsSupabase.from("poster_templates").select("template_json").eq("name", "manager-assignment-settings").maybeSingle();
  const settings = ((data?.template_json as { assignments?: AssignmentSettings } | null)?.assignments || {});
  const groups = settings.managerGroups || {}, names = settings.managerNames || {};
  const result: Record<string, string[]> = {};
  for (const [rawKey, group] of Object.entries(groups)) {
    if (["excluded", "recruitment", "new managers"].includes(group.toLowerCase())) continue;
    const label = names[rawKey] || names[rawKey.toLowerCase().replace(/[^a-z0-9]/g, "")] || `TEAM ${rawKey}`;
    const lowered = group.toLowerCase();
    const targets = [
      ["paradise", "paradise"], ["respawn", "respawn"], ["horizon", "horizon"], ["trident", "trident"], ["first-class-dan-james", "team dan"],
    ] as const;
    for (const [agencyId, needle] of targets) if (lowered.includes(needle)) (result[agencyId] ||= []).push(label.toUpperCase());
  }
  Object.values(result).forEach((list) => list.sort());
  return result;
}

export async function GET(request: Request) { try { const store = await readStore(); const includePasswords = new URL(request.url).searchParams.get("settings") === "1"; return NextResponse.json({ agencies: includePasswords ? store.agencies : store.agencies?.map(publicAgency), battles: store.battles, cardLayout: store.cardLayout, cardTypography: store.cardTypography, managers: await managerOptions() }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "COULD NOT LOAD BATTLE NETWORK." }, { status: 500 }); } }

export async function POST(request: Request) {
  try {
    const body = await request.json(); const store = await readStore(); const agencies = store.agencies || [], battles = store.battles || [];
    if (body.action === "login") { const password = String(body.password || "").trim().toUpperCase(); const agency = agencies.find((entry) => !entry.externalOnly && entry.password.toUpperCase() === password); if (!agency) return NextResponse.json({ error: "ACCESS DENIED." }, { status: 401 }); return NextResponse.json({ agency: publicAgency(agency) }); }
    if (body.action === "save-card-layout") { const layout = body.cardLayout as CardLayout; const typography = body.cardTypography as CardTypography; if (!layout || !typography) return NextResponse.json({ error: "INVALID CARD LAYOUT." }, { status: 400 }); await writeStore({ agencies, battles, cardLayout: layout, cardTypography: typography }); return NextResponse.json({ cardLayout: layout, cardTypography: typography }); }
    if (body.action === "external-login") { const password = String(body.password || "").trim().toUpperCase(); if (password !== EXTERNAL_AGENCY.password) return NextResponse.json({ error: "ACCESS DENIED." }, { status: 401 }); return NextResponse.json({ agency: publicAgency(EXTERNAL_AGENCY) }); }
    if (body.action === "external-select") { const agency = agencies.find((entry) => entry.id === key(String(body.agencyId || ""))); if (!agency?.externalOnly) return NextResponse.json({ error: "CHOOSE AN EXTERNAL AGENCY." }, { status: 400 }); const response = NextResponse.json({ agency: publicAgency(agency) }); response.cookies.set("battle-network-external-agency", agency.id, { sameSite: "lax", path: "/" }); return response; }
    if (body.action === "external-claim" && !String(body.creatorUsername || "").includes("::")) { const source = battles.find((entry) => entry.id === String(body.sourceId)); const creatorUsername = String(body.creatorUsername || "").trim().replace(/^@/, ""); const cookies = request.headers.get("cookie") || ""; const partnerId = cookies.match(/(?:^|;\\s*)battle-network-external-agency=([^;]+)/)?.[1] || ""; const partner = agencies.find((agency) => agency.id === key(partnerId)); if (!source || source.opponentBattleId || !partner?.externalOnly || !creatorUsername) return NextResponse.json({ error: "CHOOSE YOUR AGENCY AND ENTER A CREATOR USERNAME." }, { status: 409 }); const externalBattle: Battle = { id: crypto.randomUUID(), agencyId: partner.id, weekStart: source.weekStart, day: source.day, creatorUsername, manager: partner.name, size: source.size, powerUps: source.powerUps, requestedTime: source.requestedTime, actualTime: source.requestedTime, opponentBattleId: source.id, createdAt: new Date().toISOString() }; const next = battles.map((entry) => entry.id === source.id ? { ...entry, opponentBattleId: externalBattle.id } : entry); next.push(externalBattle); await writeStore({ agencies, battles: next }); return NextResponse.json({ battles: next, battle: externalBattle }); }
    if (body.action === "external-claim") { const source = battles.find((entry) => entry.id === String(body.sourceId)); const [partnerId, rawUsername] = String(body.creatorUsername || "").split("::"); const creatorUsername = rawUsername.trim().replace(/^@/, ""); const partner = agencies.find((agency) => agency.id === key(partnerId)); if (!source || source.opponentBattleId || !partner?.externalOnly || !creatorUsername) return NextResponse.json({ error: "CHOOSE YOUR AGENCY AND ENTER A CREATOR USERNAME." }, { status: 409 }); const externalBattle: Battle = { id: crypto.randomUUID(), agencyId: partner.id, weekStart: source.weekStart, day: source.day, creatorUsername, manager: partner.name, size: source.size, powerUps: source.powerUps, requestedTime: source.requestedTime, actualTime: source.requestedTime, opponentBattleId: source.id, createdAt: new Date().toISOString() }; const next = battles.map((entry) => entry.id === source.id ? { ...entry, opponentBattleId: externalBattle.id } : entry); next.push(externalBattle); await writeStore({ agencies, battles: next }); return NextResponse.json({ battles: next, battle: externalBattle }); }
    if (body.action === "register") { const name = String(body.name || "").trim().toUpperCase(), password = String(body.password || "").trim().toUpperCase(); const id = key(name); if (!name || !password || id.length < 3) return NextResponse.json({ error: "ENTER AN AGENCY NAME AND PASSWORD." }, { status: 400 }); if (agencies.some((agency) => agency.id === id)) return NextResponse.json({ error: "THAT AGENCY IS ALREADY REGISTERED." }, { status: 409 }); const agency: Agency = { id, name, password, accent: "#94a3b8", logoUrl: String(body.logoUrl || "") }; await writeStore({ agencies: [...agencies, agency], battles }); return NextResponse.json({ agency: publicAgency(agency) }); }
    if (body.action === "register-external-agency") { const name = String(body.name || "").trim().toUpperCase(), id = key(name); if (!name || id.length < 3) return NextResponse.json({ error: "ENTER AN AGENCY NAME." }, { status: 400 }); if (agencies.some((agency) => agency.id === id)) return NextResponse.json({ error: "THAT AGENCY IS ALREADY ON THE LIST." }, { status: 409 }); const agency: Agency = { id, name, password: "EXTERNAL", externalOnly: true, accent: String(body.accent || "#94a3b8"), logoUrl: String(body.logoUrl || "") }; await writeStore({ agencies: [...agencies, agency], battles }); return NextResponse.json({ agency: publicAgency(agency) }); }
    if (body.action === "save-agency") { const id = key(String(body.agency?.id || "")); if (!id || BUILT_IN_AGENCIES.some((agency) => agency.id === id)) return NextResponse.json({ error: "BUILT-IN AGENCIES ARE MANAGED THROUGH THEIR OWN PORTALS." }, { status: 400 }); const current = agencies.find((agency) => agency.id === id); const name = String(body.agency?.name || "").trim().toUpperCase(), password = String(body.agency?.password || "").trim().toUpperCase(); if (!current || !name || !password) return NextResponse.json({ error: "COMPLETE THE AGENCY DETAILS." }, { status: 400 }); const updated: Agency = { ...current, name, password, accent: String(body.agency?.accent || "#94a3b8"), logoUrl: String(body.agency?.logoUrl || "") }; const next = agencies.map((agency) => agency.id === id ? updated : agency); await writeStore({ agencies: next, battles }); return NextResponse.json({ agency: publicAgency(updated) }); }
    if (body.action === "save-external-agency") { const id = key(String(body.agency?.id || "")); const current = agencies.find((agency) => agency.id === id); const name = String(body.agency?.name || "").trim().toUpperCase(); if (!current?.externalOnly || !name) return NextResponse.json({ error: "COMPLETE THE AGENCY DETAILS." }, { status: 400 }); const updated: Agency = { ...current, name, accent: String(body.agency?.accent || "#94a3b8"), logoUrl: String(body.agency?.logoUrl || "") }; const next = agencies.map((agency) => agency.id === id ? updated : agency); await writeStore({ agencies: next, battles }); return NextResponse.json({ agency: publicAgency(updated) }); }
    if (body.action === "delete-agency") { const id = key(String(body.agencyId || "")); if (!id || BUILT_IN_AGENCIES.some((agency) => agency.id === id) || battles.some((battle) => battle.agencyId === id)) return NextResponse.json({ error: "THIS AGENCY CANNOT BE REMOVED WHILE IT HAS BATTLES." }, { status: 409 }); await writeStore({ agencies: agencies.filter((agency) => agency.id !== id), battles }); return NextResponse.json({ ok: true }); }
    if (body.action === "save-battle") { const battle = normaliseBattle(body.battle); if (!battle) return NextResponse.json({ error: "ENTER A CREATOR USERNAME." }, { status: 400 }); const existing = battles.find((entry) => entry.id === battle.id); if (existing?.opponentBattleId) return NextResponse.json({ error: "CONFIRMED BATTLES ARE LOCKED." }, { status: 409 }); const next = existing ? battles.map((entry) => entry.id === battle.id ? { ...battle, createdAt: existing.createdAt } : entry) : [battle, ...battles]; await writeStore({ agencies, battles: next }); return NextResponse.json({ battle }); }
    if (body.action === "delete-battle") { const battle = battles.find((entry) => entry.id === String(body.battleId)); const agencyId = key(String(body.agencyId || "")); if (!battle || battle.agencyId !== agencyId) return NextResponse.json({ error: "BATTLE NOT FOUND." }, { status: 404 }); if (battle.opponentBattleId) return NextResponse.json({ error: "MATCHED BATTLES CANNOT BE REMOVED." }, { status: 409 }); const next = battles.filter((entry) => entry.id !== battle.id); await writeStore({ agencies, battles: next }); return NextResponse.json({ battles: next }); }
    if (body.action === "cancel-match") { const battle = battles.find((entry) => entry.id === String(body.battleId)); const agencyId = key(String(body.agencyId || "")); if (!battle || battle.agencyId !== agencyId || !battle.opponentBattleId) return NextResponse.json({ error: "MATCHED BATTLE NOT FOUND." }, { status: 404 }); const opponentId = battle.opponentBattleId; const next = battles.map((entry) => entry.id === battle.id || entry.id === opponentId ? { ...entry, opponentBattleId: undefined, actualTime: entry.requestedTime } : entry); await writeStore({ agencies, battles: next }); return NextResponse.json({ battles: next }); }
    if (body.action === "claim-battle") { const source = battles.find((entry) => entry.id === String(body.sourceId)); const agency = agencies.find((entry) => entry.id === key(String(body.agencyId || ""))); const creatorUsername = String(body.creatorUsername || "").trim().replace(/^@/, ""); const manager = String(body.manager || "").trim(); const requestedTime = source?.requestedTime || ""; if (!source || source.opponentBattleId || !agency || !creatorUsername || !manager || !requestedTime) return NextResponse.json({ error: "COMPLETE YOUR CREATOR AND MANAGER." }, { status: 409 }); if (source.agencyId === agency.id) return NextResponse.json({ error: "CHOOSE A CREATOR FROM A DIFFERENT AVAILABLE BATTLE." }, { status: 409 }); const newBattle: Battle = { id: crypto.randomUUID(), agencyId: agency.id, weekStart: source.weekStart, day: source.day, creatorUsername, manager, size: source.size, powerUps: source.powerUps, requestedTime, actualTime: requestedTime, opponentBattleId: source.id, createdAt: new Date().toISOString() }; const next = battles.map((entry) => entry.id === source.id ? { ...entry, opponentBattleId: newBattle.id } : entry); next.push(newBattle); await writeStore({ agencies, battles: next }); return NextResponse.json({ battles: next, battle: newBattle }); }
    if (body.action === "external-claim") { const source = battles.find((entry) => entry.id === String(body.sourceId)); const creatorUsername = String(body.creatorUsername || "").trim().replace(/^@/, ""); const partner = agencies.find((agency) => agency.id === key(String(body.agencyId || ""))); if (!source || source.opponentBattleId || !partner?.externalOnly || !creatorUsername) return NextResponse.json({ error: "THAT BATTLE IS NO LONGER AVAILABLE." }, { status: 409 }); const externalBattle: Battle = { id: crypto.randomUUID(), agencyId: partner.id, weekStart: source.weekStart, day: source.day, creatorUsername, manager: partner.name, size: source.size, powerUps: source.powerUps, requestedTime: source.requestedTime, actualTime: source.requestedTime, opponentBattleId: source.id, createdAt: new Date().toISOString() }; const next = battles.map((entry) => entry.id === source.id ? { ...entry, opponentBattleId: externalBattle.id } : entry); next.push(externalBattle); await writeStore({ agencies, battles: next }); return NextResponse.json({ battles: next, battle: externalBattle }); }
    if (body.action === "add-manual-opponent") { const source = battles.find((entry) => entry.id === String(body.sourceId)); const opponentAgency = agencies.find((entry) => entry.id === key(String(body.opponentAgencyId || ""))); const creatorUsername = String(body.creatorUsername || "").trim().replace(/^@/, ""); if (!source || source.opponentBattleId || !opponentAgency || opponentAgency.id === source.agencyId || !creatorUsername) return NextResponse.json({ error: "COMPLETE THE OPPONENT DETAILS." }, { status: 409 }); const opponent: Battle = { id: crypto.randomUUID(), agencyId: opponentAgency.id, weekStart: source.weekStart, day: source.day, creatorUsername, manager: "MANUAL OPPONENT", size: source.size, powerUps: source.powerUps, requestedTime: source.requestedTime, actualTime: source.requestedTime, opponentBattleId: source.id, createdAt: new Date().toISOString() }; const next = battles.map((entry) => entry.id === source.id ? { ...entry, opponentBattleId: opponent.id } : entry); next.push(opponent); await writeStore({ agencies, battles: next }); return NextResponse.json({ battles: next, battle: opponent }); }
    if (body.action === "match") { const first = battles.find((entry) => entry.id === String(body.firstId)); const second = battles.find((entry) => entry.id === String(body.secondId)); const close = Boolean(body.close); if (!first || !second || first.id === second.id || first.opponentBattleId || second.opponentBattleId) return NextResponse.json({ error: "THAT BATTLE IS NO LONGER AVAILABLE." }, { status: 409 }); const toMinutes = (value: string) => { const [hours = "0", minutes = "0"] = value.split(":"); return Number(hours) * 60 + Number(minutes); }; const closeEnough = Math.abs(toMinutes(first.requestedTime) - toMinutes(second.requestedTime)) > 0 && Math.abs(toMinutes(first.requestedTime) - toMinutes(second.requestedTime)) <= 60 && toMinutes(first.requestedTime) >= 18 * 60 && toMinutes(second.requestedTime) >= 18 * 60; if (first.day !== second.day || first.size !== second.size || first.powerUps !== second.powerUps || (!close && first.requestedTime !== second.requestedTime) || (close && !closeEnough)) return NextResponse.json({ error: close ? "CLOSE MATCHES MUST BE WITHIN ONE HOUR AFTER 6 PM." : "BATTLES MUST MATCH ON DAY, TIME, SIZE AND POWER-UP RULES." }, { status: 409 }); const next = battles.map((entry) => entry.id === first.id ? { ...entry, opponentBattleId: second.id, actualTime: close ? second.requestedTime : first.actualTime } : entry.id === second.id ? { ...entry, opponentBattleId: first.id } : entry); await writeStore({ agencies, battles: next }); return NextResponse.json({ battles: next }); }
    return NextResponse.json({ error: "UNKNOWN BATTLE NETWORK ACTION." }, { status: 400 });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "COULD NOT SAVE BATTLE NETWORK." }, { status: 500 }); }
}
