"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Agency = { id: string; name: string; accent: string; logoUrl?: string };
type Battle = { id: string; agencyId: string; weekStart: string; day: string; creatorUsername: string; manager: string; size: string; powerUps: "POWER-UPS ALLOWED" | "NPU"; requestedTime: string; actualTime: string; opponentBattleId?: string; createdAt: string };
type Draft = Pick<Battle, "day" | "creatorUsername" | "manager" | "size" | "powerUps" | "requestedTime">;

const DAYS = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"];
const SIZES = ["LESS THAN 1K", "1 - 5K", "5K - 10K", "10K - 20K", "20K", "30K", "50K"];
const SIZE_STYLE: Record<string, string> = { "LESS THAN 1K": "bg-rose-100 text-rose-700", "1 - 5K": "bg-sky-100 text-sky-800", "5K - 10K": "bg-emerald-100 text-emerald-800", "10K - 20K": "bg-orange-100 text-orange-800", "20K": "bg-yellow-200 text-yellow-900", "30K": "bg-red-200 text-red-900", "50K": "bg-fuchsia-200 text-fuchsia-900" };
const TIMES = Array.from({ length: 96 }, (_, index) => `${String(Math.floor(index / 4)).padStart(2, "0")}:${String((index % 4) * 15).padStart(2, "0")}`);

function monday() { const date = new Date(); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date.toISOString().slice(0, 10); }
function clean(value: string) { return value.trim().replace(/^@/, ""); }
function displayTime(value: string) { const [hourText, minutes = "00"] = value.split(":"); const hour = Number(hourText); return `${hour % 12 || 12}:${minutes} ${hour >= 12 ? "PM" : "AM"}`; }
function posterRow(battle: Battle, opponent: Battle, opponentAgency: Agency) { const creatorUrl = `https://www.tiktok.com/@${clean(battle.creatorUsername).toLowerCase()}`; const opponentUrl = `https://www.tiktok.com/@${clean(opponent.creatorUsername).toLowerCase()}`; return `${battle.creatorUsername}\t${battle.manager}\t${battle.size}\t${creatorUrl}\t${displayTime(battle.requestedTime)}\t${opponentUrl}\t${displayTime(battle.actualTime)}\t${opponentAgency.name}`; }
function draftFor(day: string): Draft { return { day, creatorUsername: "", manager: "", size: "1 - 5K", powerUps: "POWER-UPS ALLOWED", requestedTime: "" }; }
function TikTokLink({ username }: { username: string }) { const name = clean(username).toLowerCase(); return <a href={`https://www.tiktok.com/@${name}`} target="_blank" rel="noreferrer" className="whitespace-nowrap text-[12px] font-bold leading-none text-sky-300 underline decoration-sky-300/50 underline-offset-2">www.tiktok.com/@{name}</a>; }
function AgencyMark({ agency }: { agency: Agency }) { const [failed, setFailed] = useState(false); return agency.logoUrl && !failed ? <img src={agency.logoUrl} alt={agency.name} onError={() => setFailed(true)} className="h-12 w-20 object-contain" /> : null; }

export default function BattleNetworkPage() {
  const [agencies, setAgencies] = useState<Agency[]>([]); const [battles, setBattles] = useState<Battle[]>([]); const [agencyId, setAgencyId] = useState(""); const [password, setPassword] = useState(""); const [tab, setTab] = useState<"SHEET" | "AVAILABLE">("SHEET"); const [week, setWeek] = useState(monday); const [status, setStatus] = useState("ENTER YOUR AGENCY PASSWORD."); const [addingDay, setAddingDay] = useState<string | null>(null); const [draft, setDraft] = useState<Draft>(draftFor("MONDAY")); const [editing, setEditing] = useState<Battle | null>(null); const [matching, setMatching] = useState<Battle | null>(null); const [claiming, setClaiming] = useState<Battle | null>(null); const [registering, setRegistering] = useState(false); const [newAgency, setNewAgency] = useState({ name: "", password: "", logoUrl: "" });
  const agency = agencies.find((item) => item.id === agencyId); const byId = (id: string) => agencies.find((item) => item.id === id);
  const own = useMemo(() => battles.filter((item) => item.agencyId === agencyId && item.weekStart === week), [battles, agencyId, week]);
  const unmatched = useMemo(() => battles.filter((item) => item.weekStart === week && !item.opponentBattleId), [battles, week]);

  async function load() { const response = await fetch("/api/battle-network", { cache: "no-store" }); const data = await response.json(); if (!response.ok) { setStatus(data.error || "COULD NOT LOAD BATTLE NETWORK."); return; } setAgencies(data.agencies || []); setBattles(data.battles || []); }
  useEffect(() => { void load(); setAgencyId(sessionStorage.getItem("battle-network-active-agency") || ""); }, []);
  async function post(body: unknown) { const response = await fetch("/api/battle-network", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setStatus(data.error || "COULD NOT SAVE."); return null; } return data; }
  async function login(event: FormEvent) { event.preventDefault(); const data = await post({ action: "login", password }); if (data) { sessionStorage.setItem("battle-network-active-agency", data.agency.id); setAgencyId(data.agency.id); setPassword(""); setStatus(`WELCOME, ${data.agency.name}.`); } }
  async function createAgency(event: FormEvent) { event.preventDefault(); const data = await post({ action: "register", ...newAgency }); if (data) { sessionStorage.setItem("battle-network-active-agency", data.agency.id); await load(); setAgencyId(data.agency.id); } }
  async function saveBattle(event: FormEvent) { event.preventDefault(); if (!agency || !draft.creatorUsername || !draft.manager || !draft.requestedTime) { setStatus("COMPLETE USERNAME, MANAGER AND TIME."); return; } const current = editing; const battle: Battle = { id: current?.id || crypto.randomUUID(), agencyId: agency.id, weekStart: current?.weekStart || week, day: draft.day, creatorUsername: clean(draft.creatorUsername), manager: draft.manager.trim(), size: draft.size, powerUps: draft.powerUps, requestedTime: draft.requestedTime, actualTime: draft.requestedTime, createdAt: current?.createdAt || new Date().toISOString() }; const data = await post({ action: "save-battle", battle }); if (data) { setBattles((rows) => current ? rows.map((row) => row.id === data.battle.id ? data.battle : row) : [data.battle, ...rows]); setAddingDay(null); setEditing(null); setStatus(current ? "BATTLE UPDATED." : "BATTLE ADDED."); } }
  function openEdit(battle: Battle) { setEditing(battle); setDraft({ day: battle.day, creatorUsername: battle.creatorUsername, manager: battle.manager, size: battle.size, powerUps: battle.powerUps || "POWER-UPS ALLOWED", requestedTime: battle.requestedTime }); setAddingDay(battle.day); }
  async function match(first: Battle, second: Battle) { const data = await post({ action: "match", firstId: first.id, secondId: second.id }); if (data) { setBattles(data.battles); setMatching(null); setStatus("BATTLE MATCHED ON BOTH SHEETS."); } }
  async function claimBattle(username: string) { if (!claiming || !username.trim() || !agency) return; const data = await post({ action: "claim-battle", sourceId: claiming.id, agencyId: agency.id, creatorUsername: username }); if (data) { setBattles(data.battles); setClaiming(null); setStatus("MATCHING BATTLE ADDED TO BOTH AGENCY SHEETS."); } }
  async function copyPosterRows(rows: Battle[]) { const completeRows = rows.flatMap((battle) => { const opponent = battles.find((item) => item.id === battle.opponentBattleId); const opponentAgency = opponent ? byId(opponent.agencyId) : undefined; return opponent && opponentAgency ? [posterRow(battle, opponent, opponentAgency)] : []; }); if (!completeRows.length) { setStatus("NO COMPLETED BATTLES TO COPY."); return; } await navigator.clipboard.writeText(completeRows.join("\n")); setStatus(`${completeRows.length} POSTER ${completeRows.length === 1 ? "ROW" : "ROWS"} COPIED.`); }
  const orderedOwn = useMemo(() => [...own].sort((a, b) => Number(Boolean(a.opponentBattleId)) - Number(Boolean(b.opponentBattleId)) || a.requestedTime.localeCompare(b.requestedTime)), [own]);
  const candidates = matching ? unmatched.filter((item) => item.id !== matching.id && item.day === matching.day && item.size === matching.size && item.requestedTime === matching.requestedTime && (item.powerUps || "POWER-UPS ALLOWED") === (matching.powerUps || "POWER-UPS ALLOWED")) : [];

  if (!agency) return <LoginScreen password={password} setPassword={setPassword} status={status} onLogin={login} registering={registering} setRegistering={setRegistering} newAgency={newAgency} setNewAgency={setNewAgency} onCreate={createAgency} />;
  return <main className="min-h-screen bg-[#050505] px-4 py-6 text-white"><div className="mx-auto max-w-[1450px]"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-5"><div className="flex items-center gap-4"><AgencyMark agency={agency}/><div><p className="text-xs font-black uppercase tracking-[.2em]" style={{ color: agency.accent }}>{agency.name}</p><h1 className="font-[family-name:var(--font-norwester)] text-4xl uppercase">BATTLE NETWORK</h1></div></div><button onClick={() => { sessionStorage.removeItem("battle-network-active-agency"); setAgencyId(""); setStatus("ENTER YOUR AGENCY PASSWORD."); }} className="rounded-lg border border-white/15 px-4 py-2 text-xs font-black uppercase">LOG OUT</button></header><div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border border-white/10 bg-white/[.03] p-1"><button onClick={() => setTab("SHEET")} className="rounded-lg px-4 py-3 text-xs font-black uppercase" style={tab === "SHEET" ? { background: agency.accent, color: "#050505" } : {}}>BATTLE SHEET</button><button onClick={() => setTab("AVAILABLE")} className="rounded-lg px-4 py-3 text-xs font-black uppercase" style={tab === "AVAILABLE" ? { background: agency.accent, color: "#050505" } : {}}>AVAILABLE CREATORS</button></div><label className="cursor-pointer text-xs font-black uppercase text-white/55">WEEK OF <input type="date" value={week} onClick={(event) => event.currentTarget.showPicker?.()} onChange={(event) => setWeek(event.target.value)} className="ml-2 cursor-pointer rounded-lg border border-white/15 bg-black p-2 text-white"/></label></div><p className="mt-4 text-xs font-black uppercase" style={{ color: agency.accent }}>{status}</p>{tab === "SHEET" ? <div className="mt-5 space-y-4">{DAYS.map((day) => <DaySection key={day} day={day} agency={agency} rows={orderedOwn.filter((item) => item.day === day)} all={battles} byId={byId} onCopyRows={copyPosterRows} onAdd={() => { setEditing(null); setDraft(draftFor(day)); setAddingDay(day); }} onEdit={openEdit} onMatch={setMatching}/>)}</div> : <Available agency={agency} rows={unmatched} own={own} byId={byId} onMatch={setMatching} onClaim={setClaiming}/>}</div>{addingDay ? <BattleModal agency={agency} draft={draft} setDraft={setDraft} editing={editing} onClose={() => { setAddingDay(null); setEditing(null); }} onSubmit={saveBattle}/> : null}{matching ? <MatchModal battle={matching} candidates={candidates} byId={byId} onClose={() => setMatching(null)} onMatch={match}/> : null}{claiming ? <ClaimModal battle={claiming} agency={agency} onClose={() => setClaiming(null)} onClaim={claimBattle}/> : null}</main>;
}

function LoginScreen({ password, setPassword, status, onLogin, registering, setRegistering, newAgency, setNewAgency, onCreate }: any) { return <main className="min-h-screen bg-[#050505] px-5 py-12 text-white"><div className="mx-auto max-w-xl"><Link href="/login" className="text-xs font-black uppercase text-yellow-200">← FIRST CLASS SPACE</Link><section className="mt-8 rounded-3xl border border-yellow-300/30 bg-white/[.035] p-7"><p className="text-xs font-black uppercase tracking-[.22em] text-yellow-200">ARRANGED BATTLES</p><h1 className="mt-3 font-[family-name:var(--font-norwester)] text-5xl uppercase">BATTLE <span className="text-yellow-300">NETWORK</span></h1>{registering ? <form onSubmit={onCreate} className="mt-8 space-y-3"><input required placeholder="AGENCY NAME" value={newAgency.name} onChange={(e) => setNewAgency((v: any) => ({ ...v, name: e.target.value }))} className="w-full rounded-xl border border-white/15 bg-black p-4 font-bold"/><input required type="password" placeholder="CREATE PASSWORD" value={newAgency.password} onChange={(e) => setNewAgency((v: any) => ({ ...v, password: e.target.value }))} className="w-full rounded-xl border border-white/15 bg-black p-4 font-bold"/><button className="w-full rounded-xl bg-yellow-300 p-4 text-xs font-black uppercase text-black">CREATE BATTLE SHEET</button></form> : <form onSubmit={onLogin} className="mt-8"><input required autoFocus type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="ENTER AGENCY PASSWORD" className="w-full rounded-xl border border-white/15 bg-black p-4 font-bold"/><button className="mt-3 w-full rounded-xl bg-yellow-300 p-4 text-xs font-black uppercase text-black">ENTER BATTLE NETWORK</button></form>}<button type="button" onClick={() => setRegistering(!registering)} className="mt-5 w-full text-xs font-black uppercase text-white/55">{registering ? "BACK TO LOGIN" : "REGISTER NEW AGENCY →"}</button><p className="mt-5 text-xs font-black uppercase text-yellow-100">{status}</p></section></div></main> }

function DaySection({ day, agency, rows, all, byId, onAdd, onEdit, onMatch, onCopyRows }: any) { return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center justify-between gap-3"><h2 className="font-[family-name:var(--font-norwester)] text-2xl uppercase" style={{ color: agency.accent }}>{day}</h2><div className="flex gap-2"><button onClick={() => onCopyRows(rows)} disabled={!rows.some((row: Battle) => row.opponentBattleId)} className="rounded-lg border border-white/15 px-4 py-2 text-xs font-black uppercase disabled:cursor-not-allowed disabled:opacity-35">COPY ALL POSTER ROWS</button><button onClick={onAdd} className="rounded-lg px-4 py-2 text-xs font-black uppercase text-black" style={{ background: agency.accent }}>ADD BATTLE</button></div></div>{rows.length ? <div className="mt-3 space-y-2">{rows.map((battle: Battle) => <BattleCard key={battle.id} battle={battle} agency={agency} opponent={all.find((item: Battle) => item.id === battle.opponentBattleId)} opponentAgency={byId(all.find((item: Battle) => item.id === battle.opponentBattleId)?.agencyId || "")} all={all} onCopyRow={onCopyRows} onEdit={onEdit} onMatch={onMatch}/>)}</div> : <p className="mt-3 text-xs font-bold uppercase text-white/35">NO BATTLES ADDED FOR {day}.</p>}</section> }

function BattleCard({ battle, agency, opponent, opponentAgency, all, onCopyRow, onEdit, onMatch }: any) {
  const matchAvailable = !opponent && all.some((item: Battle) => item.id !== battle.id && !item.opponentBattleId && item.day === battle.day && item.size === battle.size && item.requestedTime === battle.requestedTime && (item.powerUps || "POWER-UPS ALLOWED") === (battle.powerUps || "POWER-UPS ALLOWED"));
  const edge = opponent ? "border-l-emerald-400" : "border-l-red-500";
  return <article className={`grid min-h-[96px] min-w-[1290px] grid-cols-[535px_66px_500px_112px] items-center gap-3 rounded-xl border border-white/10 border-l-[6px] bg-black/55 px-5 py-3 ${edge}`}>
    <section className="grid grid-cols-[105px_95px_70px_1fr] items-center gap-3">
      <Field label="USERNAME"><strong className="block overflow-hidden text-ellipsis whitespace-nowrap font-extrabold tracking-wide" style={{ fontSize: battle.creatorUsername.length > 12 ? "0.75rem" : "0.95rem" }}>@{battle.creatorUsername}</strong></Field>
      <Field label="MANAGER"><span className="text-sm font-bold text-red-300">{battle.manager}</span></Field>
      <Field label="SIZE"><span className={`inline-block rounded-full px-3 py-1 text-xs font-black ${SIZE_STYLE[battle.size] || "bg-white/10"}`}>{battle.size}</span></Field>
      <Field label="CREATOR LINK"><TikTokLink username={battle.creatorUsername}/></Field>
    </section>
    <div className="grid place-items-center text-center"><div><p className="mb-1 text-[9px] font-black tracking-[.11em] text-white/45">{opponent ? "ACTUAL TIME" : "REQUESTED TIME"}</p><p className="text-sm font-bold">{battle.actualTime}</p><p className="mt-1 text-xl font-black" style={{ color: agency.accent }}>VS</p></div></div>
    {opponent ? <section className="grid grid-cols-[1fr_minmax(150px,1.5fr)_100px] items-center gap-4"><Field label="OPPONENT"><strong className="text-base font-extrabold tracking-wide">@{opponent.creatorUsername}</strong></Field><Field label="OPPONENT LINK"><TikTokLink username={opponent.creatorUsername}/></Field><Field label="AGENCY"><div className="flex items-center"><AgencyMark agency={opponentAgency}/><span className="text-xs font-black">{opponentAgency.name}</span></div></Field></section> : <section className="text-center"><p className="text-xs font-black text-white/45">AWAITING OPPONENT</p><p className="mt-1 text-[11px] font-bold text-white/30">{battle.size} · {battle.requestedTime} · {battle.powerUps}</p></section>}
    {opponent ? <button onClick={() => onCopyRow([battle])} className="flex items-center justify-center whitespace-nowrap text-xs font-black uppercase" style={{ color: agency.accent }}>COPY POSTER ROW</button> : <div className="flex justify-end gap-2"><button onClick={() => onEdit(battle)} title="EDIT BATTLE" className="rounded-lg border border-white/15 px-3 py-2 text-base">✎</button><button onClick={() => onMatch(battle)} className="rounded-lg border px-3 py-2 text-xs font-black uppercase" style={{ borderColor: matchAvailable ? "#34d399" : agency.accent, color: matchAvailable ? "#34d399" : agency.accent }}>{matchAvailable ? "● MATCH AVAILABLE" : "FIND OPPONENT"}</button></div>}
  </article>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { const order = label.includes("TIME") ? "order-first" : ""; const agencyField = label === "AGENCY" ? "[&_img+span]:hidden" : ""; return <div className={`battle-field min-w-0 whitespace-nowrap px-1 py-2 ${order} ${agencyField}`}><p className="mb-1 text-[9px] font-black tracking-[.11em] text-white/45">{label}</p>{children}</div> }

function Available({ agency, rows, own, byId, onMatch, onClaim }: any) { const matchFor = (battle: Battle) => own.find((mine: Battle) => mine.id !== battle.id && !mine.opponentBattleId && mine.day === battle.day && mine.size === battle.size && mine.requestedTime === battle.requestedTime && mine.powerUps === battle.powerUps); const ordered = [...rows].sort((a: Battle, b: Battle) => Number(Boolean(matchFor(b))) - Number(Boolean(matchFor(a)))); return <section className="mt-5"><h2 className="font-[family-name:var(--font-norwester)] text-3xl">AVAILABLE CREATORS</h2><div className="mt-4 flex flex-wrap gap-3">{ordered.map((battle: Battle) => { const source = byId(battle.agencyId); const mine = matchFor(battle); const canClaim = !mine && battle.agencyId !== agency.id; return <article key={battle.id} className={`w-[300px] rounded-2xl border border-l-[6px] p-4 ${mine ? "border-emerald-400/60 border-l-emerald-400 bg-emerald-400/5" : "border-white/10 border-l-red-500 bg-white/[.025]"}`}><div className="flex items-center justify-between"><AgencyMark agency={source}/>{mine ? <span className="text-[10px] font-black text-emerald-300">● MATCHABLE</span> : null}</div><strong className="mt-3 block text-lg">@{battle.creatorUsername}</strong><TikTokLink username={battle.creatorUsername}/><div className="mt-3 flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1 text-xs font-black ${SIZE_STYLE[battle.size]}`}>{battle.size}</span><span className="rounded-full border border-white/15 px-3 py-1 text-xs font-black">{battle.day} · {battle.requestedTime}</span><span className="rounded-full border border-white/15 px-3 py-1 text-xs font-black">{battle.powerUps}</span></div>{mine ? <button onClick={() => onMatch(mine)} className="mt-4 w-full rounded-lg bg-emerald-400 py-3 text-xs font-black uppercase text-black">MATCH THIS CREATOR</button> : canClaim ? <button onClick={() => onClaim(battle)} className="mt-4 w-full rounded-lg border py-3 text-xs font-black uppercase" style={{ borderColor: agency.accent, color: agency.accent }}>ADD MATCHING CREATOR</button> : null}</article> })}</div></section> }

function BattleModal({ agency, draft, setDraft, editing, onClose, onSubmit }: any) { return <div className="fixed inset-0 z-30 grid place-items-center bg-black/80 p-4"><form onSubmit={onSubmit} className="w-full max-w-xl rounded-3xl border border-white/15 bg-[#111] p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-black" style={{ color: agency.accent }}>{editing ? "EDIT BATTLE" : "ADD BATTLE"}</p><h2 className="font-[family-name:var(--font-norwester)] text-3xl">{draft.day}</h2></div><button type="button" onClick={onClose} className="text-xs font-black">CLOSE</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><input required autoFocus placeholder="USERNAME" value={draft.creatorUsername} onChange={(e) => setDraft((v: Draft) => ({ ...v, creatorUsername: e.target.value }))} className="rounded-xl border border-white/15 bg-black p-3 font-bold"/><input required placeholder="MANAGER" value={draft.manager} onChange={(e) => setDraft((v: Draft) => ({ ...v, manager: e.target.value }))} className="rounded-xl border border-white/15 bg-black p-3 font-bold"/><select value={draft.size} onChange={(e) => setDraft((v: Draft) => ({ ...v, size: e.target.value }))} className="rounded-xl border border-white/15 bg-black p-3 font-bold">{SIZES.map((size) => <option key={size}>{size}</option>)}</select><select value={draft.powerUps} onChange={(e) => setDraft((v: Draft) => ({ ...v, powerUps: e.target.value as Draft["powerUps"] }))} className="rounded-xl border border-white/15 bg-black p-3 font-bold"><option>POWER-UPS ALLOWED</option><option>NPU</option></select><select required value={draft.requestedTime} onChange={(e) => setDraft((v: Draft) => ({ ...v, requestedTime: e.target.value }))} className="rounded-xl border border-white/15 bg-black p-3 font-bold sm:col-span-2"><option value="">SELECT TIME</option>{TIMES.map((time) => <option key={time}>{time}</option>)}</select></div><p className="mt-4 text-xs text-white/55">CREATOR LINK: <TikTokLink username={draft.creatorUsername || "username"}/></p><button className="mt-6 w-full rounded-xl p-4 text-xs font-black uppercase text-black" style={{ background: agency.accent }}>{editing ? "SAVE EDIT" : "ADD BATTLE"}</button></form></div> }
function ClaimModal({ battle, agency, onClose, onClaim }: any) { const [username, setUsername] = useState(""); return <div className="fixed inset-0 z-40 grid place-items-center bg-black/85 p-4"><form onSubmit={(event) => { event.preventDefault(); onClaim(username); }} className="w-full max-w-md rounded-3xl border border-white/15 bg-[#111] p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-black" style={{ color: agency.accent }}>ADD MATCHING CREATOR</p><h2 className="mt-2 font-[family-name:var(--font-norwester)] text-3xl">{battle.requestedTime} · {battle.size}</h2></div><button type="button" onClick={onClose} className="text-xs font-black">CLOSE</button></div><p className="mt-4 text-sm text-white/60">ENTER YOUR CREATOR&apos;S USERNAME. THIS WILL ADD THE MATCHED BATTLE TO BOTH AGENCY SHEETS.</p><input required autoFocus value={username} onChange={(event) => setUsername(event.target.value)} placeholder="CREATOR USERNAME" className="mt-5 w-full rounded-xl border border-white/15 bg-black p-4 font-bold"/><button className="mt-4 w-full rounded-xl p-4 text-xs font-black uppercase text-black" style={{ background: agency.accent }}>ADD & MATCH BATTLE</button></form></div> }
function MatchModal({ battle, candidates, byId, onClose, onMatch }: any) { return <div className="fixed inset-0 z-40 grid place-items-center bg-black/85 p-4"><section className="w-full max-w-xl rounded-3xl border border-white/15 bg-[#111] p-6"><div className="flex justify-between"><div><p className="text-xs font-black text-emerald-300">MATCHABLE CREATORS</p><h2 className="font-[family-name:var(--font-norwester)] text-3xl">@{battle.creatorUsername}</h2><p className="text-sm text-white/55">{battle.day} · {battle.requestedTime} · {battle.size} · {battle.powerUps}</p></div><button onClick={onClose} className="text-xs font-black">CLOSE</button></div><div className="mt-5 space-y-2">{candidates.length ? candidates.map((candidate: Battle) => <button key={candidate.id} onClick={() => onMatch(battle, candidate)} className="flex w-full items-center justify-between rounded-xl border border-emerald-400/30 bg-emerald-400/5 p-4"><strong>@{candidate.creatorUsername}</strong><span className="text-xs font-black" style={{ color: byId(candidate.agencyId)?.accent }}>{byId(candidate.agencyId)?.name}</span></button>) : <p className="rounded-xl border border-white/10 p-4 text-sm text-white/50">NO EXACT MATCH AVAILABLE.</p>}</div></section></div> }
