import { NextResponse } from "next/server";
import { submissionsSupabase } from "@/lib/submissions-supabase";
export const dynamic = "force-dynamic";
const RECORD = "first-class-management-onboarding";
const clean = (value: unknown) => String(value || "").trim();
const managerKey = (row: Record<string, unknown>) => clean(row.manager_email || row.creator_network_manager || row["Creator Network manager"] || row.email).toLowerCase().replace(/[^a-z0-9]/g, "");
const username = (row: Record<string, unknown>) => clean(row.creator_username || row["Creator's username"]).replace(/^@/, "");
const creatorId = (row: Record<string, unknown>) => clean(row.creator_id || row["Creator ID"] || username(row));
async function entries(){const {data,error}=await submissionsSupabase.from("poster_templates").select("template_json").eq("name",RECORD).maybeSingle();if(error)throw Error(error.message);return(data?.template_json as {entries?:Record<string,unknown>})?.entries||{}}
export async function GET(request: Request){try{const selected=new URL(request.url).searchParams.get("manager")||"";const[{data:latest},{data:settings}]=await Promise.all([submissionsSupabase.from("creator_daily_stats").select("stat_date").order("stat_date",{ascending:false}).limit(1).maybeSingle(),submissionsSupabase.from("poster_templates").select("template_json").eq("name","manager-assignment-settings").maybeSingle()]);const date=clean(latest?.stat_date);if(!date)return NextResponse.json({creators:[]});const groups=((settings?.template_json as {assignments?:{managerGroups?:Record<string,string>;managerNames?:Record<string,string>}})?.assignments||{});const {data,error}=await submissionsSupabase.from("creator_daily_stats").select("*").eq("stat_date",date);if(error)throw Error(error.message);const creators=((data||[]) as Record<string,unknown>[]).filter(row=>{const key=managerKey(row);return(!selected||key===selected)&&(groups.managerGroups?.[key]||"")==="Team Dan"}).map(row=>({id:creatorId(row),username:username(row),manager:groups.managerNames?.[managerKey(row)]||managerKey(row),days:Number(row.days_since_joining||row["Days since joining"]||0)})).filter(row=>row.username&&row.days<=14);return NextResponse.json({creators,entries:await entries()})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not load onboarding"},{status:500})}}
export async function POST(request: Request){try{const body=await request.json()as{id:string;entry:unknown};const all=await entries();all[body.id]=body.entry;const{error}=await submissionsSupabase.from("poster_templates").upsert({name:RECORD,template_json:{entries:all},background_url:null,updated_at:new Date().toISOString()},{onConflict:"name"});if(error)throw Error(error.message);return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not save"},{status:500})}}
