"use client";
import { useEffect, useState } from "react";

type Manager = { key: string; name: string; group: string };
const passwordFor = (name: string) => /^(team\s+)?(dan|james)$/i.test(name.trim()) ? "DAN44" : `T${name.replace(/^team\s+/i, "").replace(/[^a-z]/gi, "").slice(0, 2).toUpperCase()}2026`;

export default function Management() {
  const [managers, setManagers] = useState<Manager[]>([]); const [selected, setSelected] = useState<Manager | null>(null); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/data-analysis/manager-assignments").then(r => r.json()).then(data => setManagers((data.managers || []).filter((item: Manager) => ["Team Dan", "Team Dan / James"].includes(item.group) && !item.name.includes(" - ")))); }, []);
  function enter(event: React.FormEvent) { event.preventDefault(); if (!selected || password.trim().toUpperCase() !== passwordFor(selected.name)) { setError("ACCESS DENIED"); return; } location.assign(`/management/${encodeURIComponent(selected.key)}?label=${encodeURIComponent(selected.name)}`); }
  return <main className="min-h-screen bg-[#080806] px-5 py-8 text-white"><div className="mx-auto max-w-6xl"><a href="/login" className="text-xs font-black uppercase tracking-widest text-yellow-200">← Go Back</a><p className="mt-10 text-xs font-black uppercase tracking-[.3em] text-yellow-200">First Class Agency</p><h1 className="mt-4 font-[family-name:var(--font-norwester)] text-5xl uppercase sm:text-7xl">Management <span className="text-yellow-300">Space</span></h1><p className="mt-4 text-white/60">Choose your team, then enter your manager password.</p><section className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{managers.length ? managers.map(item => <button key={item.key} onClick={() => { setSelected(item); setError(""); }} className={`rounded-2xl border p-5 text-left transition ${selected?.key === item.key ? "border-yellow-300 bg-yellow-300 text-black" : "border-white/15 bg-white/[.035] hover:border-yellow-300/50"}`}><span className="text-[10px] font-black uppercase tracking-[.18em] opacity-65">{item.group}</span><strong className="mt-2 block font-[family-name:var(--font-norwester)] text-2xl uppercase">{item.name}</strong></button>) : <p className="text-sm font-black uppercase text-yellow-200">Managers Loading...</p>}</section>{selected ? <form onSubmit={enter} className="mt-8 max-w-md rounded-2xl border border-yellow-300/25 bg-black/45 p-5"><p className="font-[family-name:var(--font-norwester)] text-2xl uppercase text-yellow-200">{selected.name}</p><input autoFocus type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="ENTER PASSWORD" className="mt-4 w-full rounded-xl border border-white/15 bg-black px-4 py-3 outline-none focus:border-yellow-300"/><button className="mt-3 w-full rounded-xl bg-yellow-300 py-3 text-xs font-black uppercase tracking-widest text-black">Enter Manager Space</button>{error ? <p className="mt-3 text-xs font-black text-red-300">{error}</p> : null}</form> : null}</div></main>;
}
